package phones

import (
	"strings"

	"github.com/nyaruka/phonenumbers"
)

type PhoneData struct {
	Iso2Code string `json:"iso2"`
	Name     string `json:"name"`
	Class    string `json:"class"`
	DialCode string `json:"dialcode"`
	Example  string `json:"example"`
}

func GetData() []PhoneData {
	return flags
}

func generateExample(regionCode string) string {
	return phonenumbers.Format(phonenumbers.GetExampleNumber(strings.ToUpper(regionCode)), phonenumbers.NATIONAL)
}

var flags []PhoneData = []PhoneData{
	{
		Iso2Code: "af",
		Class:    "afghanistan",
		Name:     "Afghanistan",
		DialCode: "93",
		Example:  generateExample("AF"),
	},
	{
		Iso2Code: "al",
		Class:    "albania",
		Name:     "Albania",
		DialCode: "355",
		Example:  generateExample("AL"),
	},
	{
		Iso2Code: "dz",
		Class:    "algeria",
		Name:     "Algeria",
		DialCode: "213",
		Example:  generateExample("DZ"),
	},
	{
		Iso2Code: "as",
		Class:    "american-samoa",
		Name:     "American Samoa",
		DialCode: "1",
		Example:  generateExample("AS"),
	},
	{
		Iso2Code: "ad",
		Name:     "Andorra",
		Class:    "andorra ",
		DialCode: "376",
		Example:  generateExample("AD"),
	},
	{
		Iso2Code: "ao",
		Class:    "angola",
		Name:     "Angola",
		DialCode: "244",
		Example:  generateExample("AO"),
	},
	{
		Iso2Code: "ai",
		Class:    "anguilla",
		Name:     "Anguilla",
		DialCode: "1",
		Example:  generateExample("AI"),
	},
	{
		Iso2Code: "ag",
		Class:    "antigua",
		Name:     "Antigua",
		DialCode: "1",
		Example:  generateExample("AG"),
	},
	{
		Iso2Code: "ar",
		Class:    "argentina",
		Name:     "Argentina",
		DialCode: "54",
		Example:  generateExample("AR"),
	},
	{
		Iso2Code: "am",
		Class:    "armenia",
		Name:     "Armenia",
		DialCode: "374",
		Example:  generateExample("AM"),
	},
	{
		Iso2Code: "aw",
		Class:    "aruba",
		Name:     "Aruba",
		DialCode: "297",
		Example:  generateExample("AW"),
	},
	{
		Iso2Code: "au",
		Class:    "australia",
		Name:     "Australia",
		DialCode: "61",
		Example:  generateExample("AU"),
	},
	{
		Iso2Code: "at",
		Class:    "austria",
		Name:     "Austria",
		DialCode: "43",
		Example:  generateExample("AT"),
	},
	{
		Iso2Code: "az",
		Class:    "azerbaijan",
		Name:     "Azerbaijan",
		DialCode: "994",
		Example:  generateExample("AZ"),
	},
	{
		Iso2Code: "bs",
		Class:    "bahamas",
		Name:     "Bahamas",
		DialCode: "1",
		Example:  generateExample("BS"),
	},
	{
		Iso2Code: "bh",
		Class:    "bahrain",
		Name:     "Bahrain",
		DialCode: "973",
		Example:  generateExample("BH"),
	},
	{
		Iso2Code: "bd",
		Class:    "bangladesh",
		Name:     "Bangladesh",
		DialCode: "880",
		Example:  generateExample("BD"),
	},
	{
		Iso2Code: "bb",
		Class:    "barbados",
		Name:     "Barbados",
		DialCode: "1",
		Example:  generateExample("BB"),
	},
	{
		Iso2Code: "by",
		Class:    "belarus",
		Name:     "Belarus",
		DialCode: "375",
		Example:  generateExample("BY"),
	},
	{
		Iso2Code: "be",
		Class:    "belgium",
		Name:     "Belgium",
		DialCode: "32",
		Example:  generateExample("BE"),
	},
	{
		Iso2Code: "bz",
		Class:    "belize",
		Name:     "Belize",
		DialCode: "501",
		Example:  generateExample("BZ"),
	},
	{
		Iso2Code: "bj",
		Class:    "benin",
		Name:     "Benin",
		DialCode: "229",
		Example:  generateExample("BJ"),
	},
	{
		Iso2Code: "bm",
		Class:    "bermuda",
		Name:     "Bermuda",
		DialCode: "1",
		Example:  generateExample("BM"),
	},
	{
		Iso2Code: "bt",
		Class:    "bhutan",
		Name:     "Bhutan",
		DialCode: "975",
		Example:  generateExample("BT"),
	},
	{
		Iso2Code: "bo",
		Class:    "bolivia",
		Name:     "Bolivia",
		DialCode: "591",
		Example:  generateExample("BO"),
	},
	{
		Iso2Code: "ba",
		Class:    "bosnia",
		Name:     "Bosnia and Herzegovina",
		DialCode: "387",
		Example:  generateExample("BA"),
	},
	{
		Iso2Code: "bw",
		Class:    "botswana",
		Name:     "Botswana",
		DialCode: "267",
		Example:  generateExample("BW"),
	},
	{
		Iso2Code: "br",
		Class:    "brazil",
		Name:     "Brazil",
		DialCode: "55",
		Example:  generateExample("BR"),
	},
	{
		Iso2Code: "io",
		Class:    "indian-ocean-territory",
		Name:     "Indian Ocean Territory",
		DialCode: "246",
		Example:  generateExample("IO"),
	},
	{
		Iso2Code: "vg",
		Class:    "british-virgin-islands",
		Name:     "British Virgin Islands",
		DialCode: "1",
		Example:  generateExample("VG"),
	},
	{
		Iso2Code: "bn",
		Class:    "brunei",
		Name:     "Brunei",
		DialCode: "673",
		Example:  generateExample("BN"),
	},
	{
		Iso2Code: "bg",
		Class:    "bulgaria",
		Name:     "Bulgaria",
		DialCode: "359",
		Example:  generateExample("BG"),
	},
	{
		Iso2Code: "bf",
		Class:    "burkina-faso",
		Name:     "Burkina Faso",
		DialCode: "226",
		Example:  generateExample("BF"),
	},
	{
		Iso2Code: "bi",
		Class:    "burundi",
		Name:     "Burundi",
		DialCode: "257",
		Example:  generateExample("BI"),
	},
	{
		Iso2Code: "kh",
		Class:    "cambodia",
		Name:     "Cambodia",
		DialCode: "855",
		Example:  generateExample("KH"),
	},
	{
		Iso2Code: "cm",
		Class:    "cameroon",
		Name:     "Cameroon",
		DialCode: "237",
		Example:  generateExample("CM"),
	},
	{
		Iso2Code: "ca",
		Class:    "canada",
		Name:     "Canada",
		DialCode: "1",
		Example:  generateExample("CA"),
	},
	{
		Iso2Code: "cv",
		Class:    "cape-verde",
		Name:     "Cape Verde",
		DialCode: "238",
		Example:  generateExample("CV"),
	},
	{
		Iso2Code: "ky",
		Class:    "cayman-islands",
		Name:     "Cayman Islands",
		DialCode: "1",
		Example:  generateExample("KY"),
	},
	{
		Iso2Code: "cf",
		Class:    "central-african-republic",
		Name:     "Central African Republic",
		DialCode: "236",
		Example:  generateExample("CF"),
	},
	{
		Iso2Code: "td",
		Class:    "chad",
		Name:     "Chad",
		DialCode: "235",
		Example:  generateExample("TD"),
	},
	{
		Iso2Code: "cl",
		Class:    "chile",
		Name:     "Chile",
		DialCode: "56",
		Example:  generateExample("CL"),
	},
	{
		Iso2Code: "cn",
		Class:    "china",
		Name:     "China",
		DialCode: "86",
		Example:  generateExample("CN"),
	},
	{
		Iso2Code: "cx",
		Class:    "christmas-island",
		Name:     "Christmas Island",
		DialCode: "61",
		Example:  generateExample("CX"),
	},
	{
		Iso2Code: "cc",
		Class:    "cocos-islands",
		Name:     "Cocos Islands",
		DialCode: "61",
		Example:  generateExample("CC"),
	},
	{
		Iso2Code: "co",
		Class:    "colombia",
		Name:     "Colombia",
		DialCode: "57",
		Example:  generateExample("CO"),
	},
	{
		Iso2Code: "km",
		Class:    "comoros",
		Name:     "Comoros",
		DialCode: "269",
		Example:  generateExample("KM"),
	},
	{
		Iso2Code: "cg",
		Class:    "congo-brazzaville",
		Name:     "Congo Brazzaville",
		DialCode: "242",
		Example:  generateExample("CG"),
	},
	{
		Iso2Code: "cd",
		Class:    "congo",
		Name:     "Congo",
		DialCode: "243",
		Example:  generateExample("CD"),
	},
	{
		Iso2Code: "ck",
		Class:    "cook-islands",
		Name:     "Cook Islands",
		DialCode: "682",
		Example:  generateExample("CK"),
	},
	{
		Iso2Code: "cr",
		Class:    "costa-rica",
		Name:     "Costa Rica",
		DialCode: "506",
		Example:  generateExample("CR"),
	},
	{
		Iso2Code: "ci",
		Class:    "cote-divoire",
		Name:     "Cote Divoire",
		DialCode: "225",
		Example:  generateExample("CI"),
	},
	{
		Iso2Code: "hr",
		Class:    "croatia",
		Name:     "Croatia",
		DialCode: "385",
		Example:  generateExample("HR"),
	},
	{
		Iso2Code: "cu",
		Class:    "cuba",
		Name:     "Cuba",
		DialCode: "53",
		Example:  generateExample("CU"),
	},
	{
		Iso2Code: "cy",
		Class:    "cyprus",
		Name:     "Cyprus",
		DialCode: "357",
		Example:  generateExample("CY"),
	},
	{
		Iso2Code: "cz",
		Class:    "czech-republic",
		Name:     "Czech Republic",
		DialCode: "420",
		Example:  generateExample("CZ"),
	},
	{
		Iso2Code: "dk",
		Class:    "denmark",
		Name:     "Denmark",
		DialCode: "45",
		Example:  generateExample("DK"),
	},
	{
		Iso2Code: "dj",
		Class:    "djibouti",
		Name:     "Djibouti",
		DialCode: "253",
		Example:  generateExample("DJ"),
	},
	{
		Iso2Code: "dm",
		Class:    "dominica",
		Name:     "Dominica",
		DialCode: "1",
		Example:  generateExample("DM"),
	},
	{
		Iso2Code: "do",
		Class:    "dominican-republic",
		Name:     "Dominican Republic",
		DialCode: "1",
		Example:  generateExample("DO"),
	},
	{
		Iso2Code: "ec",
		Class:    "ecuador",
		Name:     "Ecuador",
		DialCode: "593",
		Example:  generateExample("EC"),
	},
	{
		Iso2Code: "eg",
		Class:    "egypt",
		Name:     "Egypt",
		DialCode: "20",
		Example:  generateExample("EG"),
	},
	{
		Iso2Code: "sv",
		Class:    "el salvador",
		Name:     "El Salvador",
		DialCode: "503",
		Example:  generateExample("SV"),
	},
	{
		Iso2Code: "gq",
		Class:    "equatorial-guinea",
		Name:     "Equatorial Guinea",
		DialCode: "240",
		Example:  generateExample("GQ"),
	},
	{
		Iso2Code: "er",
		Class:    "eritrea",
		Name:     "Eritrea",
		DialCode: "291",
		Example:  generateExample("ER"),
	},
	{
		Iso2Code: "ee",
		Class:    "estonia",
		Name:     "Estonia",
		DialCode: "372",
		Example:  generateExample("EE"),
	},
	{
		Iso2Code: "sz",
		Class:    "swaziland",
		Name:     "Swaziland",
		DialCode: "268",
		Example:  generateExample("SZ"),
	},
	{
		Iso2Code: "et",
		Class:    "ethiopia",
		Name:     "Ethiopia",
		DialCode: "251",
		Example:  generateExample("ET"),
	},
	{
		Iso2Code: "fk",
		Class:    "falkland-islands",
		Name:     "Falkland Islands",
		DialCode: "500",
		Example:  generateExample("FK"),
	},
	{
		Iso2Code: "fo",
		Class:    "faroe-islands",
		Name:     "Faroe Islands",
		DialCode: "298",
		Example:  generateExample("FO"),
	},
	{
		Iso2Code: "fj",
		Class:    "fiji",
		Name:     "Fiji",
		DialCode: "679",
		Example:  generateExample("FJ"),
	},
	{
		Iso2Code: "fi",
		Class:    "finland",
		Name:     "Finland",
		DialCode: "358",
		Example:  generateExample("FI"),
	},
	{
		Iso2Code: "fr",
		Class:    "france",
		Name:     "France",
		DialCode: "33",
		Example:  generateExample("FR"),
	},
	{
		Iso2Code: "gf",
		Class:    "french-guiana",
		Name:     "French Guiana",
		DialCode: "594",
		Example:  generateExample("GF"),
	},
	{
		Iso2Code: "pf",
		Class:    "french-polynesia",
		Name:     "French Polynesia",
		DialCode: "689",
		Example:  generateExample("PF"),
	},
	{
		Iso2Code: "ga",
		Class:    "gabon",
		Name:     "Gabon",
		DialCode: "241",
		Example:  generateExample("GA"),
	},
	{
		Iso2Code: "gm",
		Class:    "gambia",
		Name:     "Gambia",
		DialCode: "220",
		Example:  generateExample("GM"),
	},
	{
		Iso2Code: "ge",
		Class:    "georgia",
		Name:     "Georgia",
		DialCode: "995",
		Example:  generateExample("GE"),
	},
	{
		Iso2Code: "de",
		Class:    "germany",
		Name:     "Germany",
		DialCode: "49",
		Example:  generateExample("DE"),
	},
	{
		Iso2Code: "gh",
		Class:    "ghana",
		Name:     "Ghana",
		DialCode: "233",
		Example:  generateExample("GH"),
	},
	{
		Iso2Code: "gi",
		Class:    "gibraltar",
		Name:     "Gibraltar",
		DialCode: "350",
		Example:  generateExample("GI"),
	},
	{
		Iso2Code: "gr",
		Class:    "greece",
		Name:     "Greece",
		DialCode: "30",
		Example:  generateExample("GR"),
	},
	{
		Iso2Code: "gl",
		Class:    "greenland",
		Name:     "Greenland",
		DialCode: "299",
		Example:  generateExample("GL"),
	},
	{
		Iso2Code: "gd",
		Class:    "grenada",
		Name:     "Grenada",
		DialCode: "1",
		Example:  generateExample("GD"),
	},
	{
		Iso2Code: "gp",
		Class:    "guadeloupe",
		Name:     "Guadeloupe",
		DialCode: "590",
		Example:  generateExample("GP"),
	},
	{
		Iso2Code: "gu",
		Class:    "guam",
		Name:     "Guam",
		DialCode: "1",
		Example:  generateExample("GU"),
	},
	{
		Iso2Code: "gt",
		Class:    "guatemala",
		Name:     "Guatemala",
		DialCode: "502",
		Example:  generateExample("GT"),
	},
	{
		Iso2Code: "gg",
		Class:    "england",
		Name:     "England",
		DialCode: "44",
		Example:  generateExample("GG"),
	},
	{
		Iso2Code: "gn",
		Class:    "guinea",
		Name:     "Guinea",
		DialCode: "224",
		Example:  generateExample("GN"),
	},
	{
		Iso2Code: "gw",
		Class:    "guinea-bissau",
		Name:     "Guinea-bissau",
		DialCode: "245",
		Example:  generateExample("GW"),
	},
	{
		Iso2Code: "gy",
		Class:    "guyana",
		Name:     "Guyana",
		DialCode: "592",
		Example:  generateExample("GY"),
	},
	{
		Iso2Code: "ht",
		Class:    "haiti",
		Name:     "Haiti",
		DialCode: "509",
		Example:  generateExample("HT"),
	},
	{
		Iso2Code: "hn",
		Class:    "honduras",
		Name:     "Honduras",
		DialCode: "504",
		Example:  generateExample("HN"),
	},
	{
		Iso2Code: "hk",
		Class:    "hong-kong",
		Name:     "Hong Kong",
		DialCode: "852",
		Example:  generateExample("HK"),
	},
	{
		Iso2Code: "hu",
		Class:    "hungary",
		Name:     "Hungary",
		DialCode: "36",
		Example:  generateExample("HU"),
	},
	{
		Iso2Code: "is",
		Class:    "iceland",
		Name:     "Iceland",
		DialCode: "354",
		Example:  generateExample("IS"),
	},
	{
		Iso2Code: "in",
		Class:    "india",
		Name:     "India",
		DialCode: "91",
		Example:  generateExample("IN"),
	},
	{
		Iso2Code: "id",
		Class:    "indonesia",
		Name:     "Indonesia",
		DialCode: "62",
		Example:  generateExample("ID"),
	},
	{
		Iso2Code: "ir",
		Class:    "iran",
		Name:     "Iran",
		DialCode: "98",
		Example:  generateExample("IR"),
	},
	{
		Iso2Code: "iq",
		Class:    "iraq",
		Name:     "Iraq",
		DialCode: "964",
		Example:  generateExample("IQ"),
	},
	{
		Iso2Code: "ie",
		Class:    "ireland",
		Name:     "Ireland",
		DialCode: "353",
		Example:  generateExample("IE"),
	},
	{
		Iso2Code: "il",
		Class:    "israel",
		Name:     "Israel",
		DialCode: "972",
		Example:  generateExample("IL"),
	},
	{
		Iso2Code: "it",
		Class:    "italy",
		Name:     "Italy",
		DialCode: "39",
		Example:  generateExample("IT"),
	},
	{
		Iso2Code: "jm",
		Class:    "jamaica",
		Name:     "Jamaica",
		DialCode: "1",
		Example:  generateExample("JM"),
	},
	{
		Iso2Code: "jp",
		Class:    "japan",
		Name:     "Japan",
		DialCode: "81",
		Example:  generateExample("JP"),
	},
	{
		Iso2Code: "je",
		Class:    "england",
		Name:     "England",
		DialCode: "44",
		Example:  generateExample("JE"),
	},
	{
		Iso2Code: "jo",
		Class:    "jordan",
		Name:     "Jordan",
		DialCode: "962",
		Example:  generateExample("JO"),
	},
	{
		Iso2Code: "kz",
		Class:    "kazakhstan",
		Name:     "Kazakhstan",
		DialCode: "7",
		Example:  generateExample("KZ"),
	},
	{
		Iso2Code: "ke",
		Class:    "kenya",
		Name:     "Kenya",
		DialCode: "254",
		Example:  generateExample("KE"),
	},
	{
		Iso2Code: "ki",
		Class:    "kiribati",
		Name:     "Kiribati",
		DialCode: "686",
		Example:  generateExample("KI"),
	},
	{
		Iso2Code: "kw",
		Class:    "kuwait",
		Name:     "Kuwait",
		DialCode: "965",
		Example:  generateExample("KW"),
	},
	{
		Iso2Code: "kg",
		Class:    "kyrgyzstan",
		Name:     "Kyrgyzstan",
		DialCode: "996",
		Example:  generateExample("KG"),
	},
	{
		Iso2Code: "la",
		Class:    "laos",
		Name:     "Laos",
		DialCode: "856",
		Example:  generateExample("LA"),
	},
	{
		Iso2Code: "lv",
		Class:    "latvia",
		Name:     "Latvia",
		DialCode: "371",
		Example:  generateExample("LV"),
	},
	{
		Iso2Code: "lb",
		Class:    "lebanon",
		Name:     "Lebanon",
		DialCode: "961",
		Example:  generateExample("LB"),
	},
	{
		Iso2Code: "ls",
		Class:    "lesotho",
		Name:     "Lesotho",
		DialCode: "266",
		Example:  generateExample("LS"),
	},
	{
		Iso2Code: "lr",
		Class:    "liberia",
		Name:     "Liberia",
		DialCode: "231",
		Example:  generateExample("LR"),
	},
	{
		Iso2Code: "ly",
		Class:    "libya",
		Name:     "Libya",
		DialCode: "218",
		Example:  generateExample("LY"),
	},
	{
		Iso2Code: "li",
		Class:    "liechtenstein",
		Name:     "Liechtenstein",
		DialCode: "423",
		Example:  generateExample("LI"),
	},
	{
		Iso2Code: "lt",
		Class:    "lithuania",
		Name:     "Lithuania",
		DialCode: "370",
		Example:  generateExample("LT"),
	},
	{
		Iso2Code: "lu",
		Class:    "luxembourg",
		Name:     "Luxembourg",
		DialCode: "352",
		Example:  generateExample("LU"),
	},
	{
		Iso2Code: "mo",
		Class:    "macau",
		Name:     "Macau",
		DialCode: "853",
		Example:  generateExample("MO"),
	},
	{
		Iso2Code: "mg",
		Class:    "madagascar",
		Name:     "Madagascar",
		DialCode: "261",
		Example:  generateExample("MG"),
	},
	{
		Iso2Code: "mw",
		Class:    "malawi",
		Name:     "Malawi",
		DialCode: "265",
		Example:  generateExample("MW"),
	},
	{
		Iso2Code: "my",
		Class:    "malaysia",
		Name:     "Malaysia",
		DialCode: "60",
		Example:  generateExample("MY"),
	},
	{
		Iso2Code: "mv",
		Class:    "maldives",
		Name:     "Maldives",
		DialCode: "960",
		Example:  generateExample("MV"),
	},
	{
		Iso2Code: "ml",
		Class:    "mali",
		Name:     "Mali",
		DialCode: "223",
		Example:  generateExample("ML"),
	},
	{
		Iso2Code: "mt",
		Class:    "malta",
		Name:     "Malta",
		DialCode: "356",
		Example:  generateExample("MT"),
	},
	{
		Iso2Code: "mh",
		Class:    "marshall-islands",
		Name:     "Marshall Islands",
		DialCode: "692",
		Example:  generateExample("MH"),
	},
	{
		Iso2Code: "mq",
		Class:    "martinique",
		Name:     "Martinique",
		DialCode: "596",
		Example:  generateExample("MQ"),
	},
	{
		Iso2Code: "mr",
		Class:    "mauritania",
		Name:     "Mauritania",
		DialCode: "222",
		Example:  generateExample("MR"),
	},
	{
		Iso2Code: "mu",
		Class:    "mauritius",
		Name:     "Mauritius",
		DialCode: "230",
		Example:  generateExample("MU"),
	},
	{
		Iso2Code: "yt",
		Class:    "mayotte",
		Name:     "Mayotte",
		DialCode: "262",
		Example:  generateExample("YT"),
	},
	{
		Iso2Code: "mx",
		Class:    "mexico",
		Name:     "Mexico",
		DialCode: "52",
		Example:  generateExample("MX"),
	},
	{
		Iso2Code: "fm",
		Class:    "micronesia",
		Name:     "Micronesia",
		DialCode: "691",
		Example:  generateExample("FM"),
	},
	{
		Iso2Code: "md",
		Class:    "moldova",
		Name:     "Moldova",
		DialCode: "373",
		Example:  generateExample("MD"),
	},
	{
		Iso2Code: "mc",
		Class:    "monaco",
		Name:     "Monaco",
		DialCode: "377",
		Example:  generateExample("MC"),
	},
	{
		Iso2Code: "mn",
		Class:    "mongolia",
		Name:     "Mongolia",
		DialCode: "976",
		Example:  generateExample("MN"),
	},
	{
		Iso2Code: "me",
		Class:    "montenegro",
		Name:     "Montenegro",
		DialCode: "382",
		Example:  generateExample("ME"),
	},
	{
		Iso2Code: "ms",
		Class:    "montserrat",
		Name:     "Montserrat",
		DialCode: "1",
		Example:  generateExample("MS"),
	},
	{
		Iso2Code: "ma",
		Class:    "morocco",
		Name:     "Morocco",
		DialCode: "212",
		Example:  generateExample("MA"),
	},
	{
		Iso2Code: "mz",
		Class:    "mozambique",
		Name:     "Mozambique",
		DialCode: "258",
		Example:  generateExample("MZ"),
	},
	{
		Iso2Code: "mm",
		Class:    "burma",
		Name:     "Burma",
		DialCode: "95",
		Example:  generateExample("MM"),
	},
	{
		Iso2Code: "na",
		Class:    "namibia",
		Name:     "Namibia",
		DialCode: "264",
		Example:  generateExample("NA"),
	},
	{
		Iso2Code: "nr",
		Class:    "nauru",
		Name:     "Nauru",
		DialCode: "674",
		Example:  generateExample("NR"),
	},
	{
		Iso2Code: "np",
		Class:    "nepal",
		Name:     "Nepal",
		DialCode: "977",
		Example:  generateExample("NP"),
	},
	{
		Iso2Code: "nl",
		Class:    "netherlands",
		Name:     "Netherlands",
		DialCode: "31",
		Example:  generateExample("NL"),
	},
	{
		Iso2Code: "nc",
		Class:    "new-caledonia",
		Name:     "New Caledonia",
		DialCode: "687",
		Example:  generateExample("NC"),
	},
	{
		Iso2Code: "nz",
		Class:    "new-zealand",
		Name:     "New Zealand",
		DialCode: "64",
		Example:  generateExample("NZ"),
	},
	{
		Iso2Code: "ni",
		Class:    "nicaragua",
		Name:     "Nicaragua",
		DialCode: "505",
		Example:  generateExample("NI"),
	},
	{
		Iso2Code: "ne",
		Class:    "niger",
		Name:     "Niger",
		DialCode: "227",
		Example:  generateExample("NE"),
	},
	{
		Iso2Code: "ng",
		Class:    "nigeria",
		Name:     "Nigeria",
		DialCode: "234",
		Example:  generateExample("NG"),
	},
	{
		Iso2Code: "nu",
		Class:    "niue",
		Name:     "Niue",
		DialCode: "683",
		Example:  generateExample("NU"),
	},
	{
		Iso2Code: "nf",
		Class:    "norfolk-island",
		Name:     "Norfolk Island",
		DialCode: "672",
		Example:  generateExample("NF"),
	},
	{
		Iso2Code: "kp",
		Class:    "north-korea",
		Name:     "North Korea",
		DialCode: "850",
		Example:  generateExample("KP"),
	},
	{
		Iso2Code: "mk",
		Class:    "macedonia",
		Name:     "North Macedonia",
		DialCode: "389",
		Example:  generateExample("MK"),
	},
	{
		Iso2Code: "mp",
		Class:    "northern-mariana-islands",
		Name:     "Northern Mariana Islands",
		DialCode: "1",
		Example:  generateExample("MP"),
	},
	{
		Iso2Code: "no",
		Class:    "norway",
		Name:     "Norway",
		DialCode: "47",
		Example:  generateExample("NO"),
	},
	{
		Iso2Code: "om",
		Class:    "oman",
		Name:     "Oman",
		DialCode: "968",
		Example:  generateExample("OM"),
	},
	{
		Iso2Code: "pk",
		Class:    "pakistan",
		Name:     "Pakistan",
		DialCode: "92",
		Example:  generateExample("PK"),
	},
	{
		Iso2Code: "pw",
		Class:    "palau",
		Name:     "Palau",
		DialCode: "680",
		Example:  generateExample("PW"),
	},
	{
		Iso2Code: "ps",
		Class:    "palestine",
		Name:     "Palestine",
		DialCode: "970",
		Example:  generateExample("PS"),
	},
	{
		Iso2Code: "pa",
		Class:    "panama",
		Name:     "Panama",
		DialCode: "507",
		Example:  generateExample("PA"),
	},
	{
		Iso2Code: "pg",
		Class:    "new-guinea",
		Name:     "New Guinea",
		DialCode: "675",
		Example:  generateExample("PG"),
	},
	{
		Iso2Code: "py",
		Class:    "paraguay",
		Name:     "Paraguay",
		DialCode: "595",
		Example:  generateExample("PY"),
	},
	{
		Iso2Code: "pe",
		Class:    "peru",
		Name:     "Peru",
		DialCode: "51",
		Example:  generateExample("PE"),
	},
	{
		Iso2Code: "ph",
		Class:    "philippines",
		Name:     "Philippines",
		DialCode: "63",
		Example:  generateExample("PH"),
	},
	{
		Iso2Code: "pl",
		Class:    "poland",
		Name:     "Poland",
		DialCode: "48",
		Example:  generateExample("PL"),
	},
	{
		Iso2Code: "pt",
		Class:    "portugal",
		Name:     "Portugal",
		DialCode: "351",
		Example:  generateExample("PT"),
	},
	{
		Iso2Code: "pr",
		Class:    "puerto-rico",
		Name:     "Puerto Rico",
		DialCode: "1",
		Example:  generateExample("PR"),
	},
	{
		Iso2Code: "qa",
		Class:    "qatar",
		Name:     "Qatar",
		DialCode: "974",
		Example:  generateExample("QA"),
	},
	{
		Iso2Code: "re",
		Class:    "reunion",
		Name:     "Reunion",
		DialCode: "262",
		Example:  generateExample("RE"),
	},
	{
		Iso2Code: "ro",
		Class:    "romania",
		Name:     "Romania",
		DialCode: "40",
		Example:  generateExample("RO"),
	},
	{
		Iso2Code: "ru",
		Class:    "russia",
		Name:     "Russia",
		DialCode: "7",
		Example:  generateExample("RU"),
	},
	{
		Iso2Code: "rw",
		Class:    "rwanda",
		Name:     "Rwanda",
		DialCode: "250",
		Example:  generateExample("RW"),
	},
	{
		Iso2Code: "ws",
		Class:    "samoa",
		Name:     "Samoa",
		DialCode: "685",
		Example:  generateExample("WS"),
	},
	{
		Iso2Code: "sm",
		Class:    "san-marino",
		Name:     "San Marino",
		DialCode: "378",
		Example:  generateExample("SM"),
	},
	{
		Iso2Code: "st",
		Class:    "sao-tome",
		Name:     "Sao Tome",
		DialCode: "239",
		Example:  generateExample("ST"),
	},
	{
		Iso2Code: "sa",
		Class:    "saudi-arabia",
		Name:     "Saudi Arabia",
		DialCode: "966",
		Example:  generateExample("SA"),
	},
	{
		Iso2Code: "sn",
		Class:    "senegal",
		Name:     "Senegal",
		DialCode: "221",
		Example:  generateExample("SN"),
	},
	{
		Iso2Code: "rs",
		Class:    "serbia",
		Name:     "Serbia",
		DialCode: "381",
		Example:  generateExample("RS"),
	},
	{
		Iso2Code: "sc",
		Class:    "seychelles",
		Name:     "Seychelles",
		DialCode: "248",
		Example:  generateExample("SC"),
	},
	{
		Iso2Code: "sl",
		Class:    "sierra-leone",
		Name:     "Sierra Leone",
		DialCode: "232",
		Example:  generateExample("SL"),
	},
	{
		Iso2Code: "sg",
		Class:    "singapore",
		Name:     "Singapore",
		DialCode: "65",
		Example:  generateExample("SG"),
	},
	{
		Iso2Code: "sk",
		Class:    "slovakia",
		Name:     "Slovakia",
		DialCode: "421",
		Example:  generateExample("SK"),
	},
	{
		Iso2Code: "si",
		Class:    "slovenia",
		Name:     "Slovenia",
		DialCode: "386",
		Example:  generateExample("SI"),
	},
	{
		Iso2Code: "sb",
		Class:    "solomon-islands",
		Name:     "Solomon Islands",
		DialCode: "677",
		Example:  generateExample("SB"),
	},
	{
		Iso2Code: "so",
		Class:    "somalia",
		Name:     "Somalia",
		DialCode: "252",
		Example:  generateExample("SO"),
	},
	{
		Iso2Code: "za",
		Class:    "south-africa",
		Name:     "South Africa",
		DialCode: "27",
		Example:  generateExample("ZA"),
	},
	{
		Iso2Code: "kr",
		Class:    "south-korea",
		Name:     "South Korea",
		DialCode: "82",
		Example:  generateExample("KR"),
	},
	{
		Iso2Code: "es",
		Class:    "spain",
		Name:     "Spain",
		DialCode: "34",
		Example:  generateExample("ES"),
	},
	{
		Iso2Code: "lk",
		Class:    "sri-lanka",
		Name:     "Sri Lanka",
		DialCode: "94",
		Example:  generateExample("LK"),
	},
	{
		Iso2Code: "sh",
		Class:    "saint-helena",
		Name:     "Saint Helena",
		DialCode: "290",
		Example:  generateExample("SH"),
	},
	{
		Iso2Code: "kn",
		Class:    "saint-kitts-and-nevis",
		Name:     "Saint Kitts And Nevis",
		DialCode: "1",
		Example:  generateExample("KN"),
	},
	{
		Iso2Code: "lc",
		Class:    "saint-lucia",
		Name:     "Saint Lucia",
		DialCode: "1",
		Example:  generateExample("LC"),
	},
	{
		Iso2Code: "pm",
		Class:    "saint-pierre",
		Name:     "Saint Pierre",
		DialCode: "508",
		Example:  generateExample("PM"),
	},
	{
		Iso2Code: "vc",
		Class:    "saint-vincent",
		Name:     "Saint Vincent",
		DialCode: "1",
		Example:  generateExample("VC"),
	},
	{
		Iso2Code: "sd",
		Class:    "sudan",
		Name:     "Sudan",
		DialCode: "249",
		Example:  generateExample("SD"),
	},
	{
		Iso2Code: "sr",
		Class:    "suriname",
		Name:     "Suriname",
		DialCode: "597",
		Example:  generateExample("SR"),
	},
	{
		Iso2Code: "sj",
		Class:    "jan-mayen",
		Name:     "Jan Mayen",
		DialCode: "47",
		Example:  generateExample("SJ"),
	},
	{
		Iso2Code: "se",
		Class:    "sweden",
		Name:     "Sweden",
		DialCode: "46",
		Example:  generateExample("SE"),
	},
	{
		Iso2Code: "ch",
		Class:    "switzerland",
		Name:     "Switzerland",
		DialCode: "41",
		Example:  generateExample("CH"),
	},
	{
		Iso2Code: "sy",
		Class:    "syria",
		Name:     "Syria",
		DialCode: "963",
		Example:  generateExample("SY"),
	},
	{
		Iso2Code: "tw",
		Class:    "taiwan",
		Name:     "Taiwan",
		DialCode: "886",
		Example:  generateExample("TW"),
	},
	{
		Iso2Code: "tj",
		Class:    "tajikistan",
		Name:     "Tajikistan",
		DialCode: "992",
		Example:  generateExample("TJ"),
	},
	{
		Iso2Code: "tz",
		Class:    "tanzania",
		Name:     "Tanzania",
		DialCode: "255",
		Example:  generateExample("TZ"),
	},
	{
		Iso2Code: "th",
		Class:    "thailand",
		Name:     "Thailand",
		DialCode: "66",
		Example:  generateExample("TH"),
	},
	{
		Iso2Code: "tl",
		Class:    "timorleste",
		Name:     "Timorleste",
		DialCode: "670",
		Example:  generateExample("TL"),
	},
	{
		Iso2Code: "tg",
		Class:    "togo",
		Name:     "Togo",
		DialCode: "228",
		Example:  generateExample("TG"),
	},
	{
		Iso2Code: "tk",
		Class:    "tokelau",
		Name:     "Tokelau",
		DialCode: "690",
		Example:  generateExample("TK"),
	},
	{
		Iso2Code: "to",
		Class:    "tonga",
		Name:     "Tonga",
		DialCode: "676",
		Example:  generateExample("TO"),
	},
	{
		Iso2Code: "tt",
		Class:    "trinidad",
		Name:     "Trinidad",
		DialCode: "1",
		Example:  generateExample("TT"),
	},
	{
		Iso2Code: "tn",
		Class:    "tunisia",
		Name:     "Tunisia",
		DialCode: "216",
		Example:  generateExample("TN"),
	},
	{
		Iso2Code: "tr",
		Class:    "turkey",
		Name:     "Turkey",
		DialCode: "90",
		Example:  generateExample("TR"),
	},
	{
		Iso2Code: "tm",
		Class:    "turkmenistan",
		Name:     "Turkmenistan",
		DialCode: "993",
		Example:  generateExample("TM"),
	},
	{
		Iso2Code: "tc",
		Class:    "caicos-islands",
		Name:     "Caicos Islands",
		DialCode: "1",
		Example:  generateExample("TC"),
	},
	{
		Iso2Code: "tv",
		Class:    "tuvalu",
		Name:     "Tuvalu",
		DialCode: "688",
		Example:  generateExample("TV"),
	},
	{
		Iso2Code: "ug",
		Class:    "uganda",
		Name:     "Uganda",
		DialCode: "256",
		Example:  generateExample("UG"),
	},
	{
		Iso2Code: "ua",
		Class:    "ukraine",
		Name:     "Ukraine",
		DialCode: "380",
		Example:  generateExample("UA"),
	},
	{
		Iso2Code: "ae",
		Class:    "uae",
		Name:     "U.A.E",
		DialCode: "971",
		Example:  generateExample("AE"),
	},
	{
		Iso2Code: "gb",
		Class:    "england",
		Name:     "England",
		DialCode: "44",
		Example:  generateExample("GB"),
	},
	{
		Iso2Code: "us",
		Class:    "united states",
		Name:     "United States",
		DialCode: "1",
		Example:  generateExample("US"),
	},
	{
		Iso2Code: "uy",
		Class:    "uruguay",
		Name:     "Uruguay",
		DialCode: "598",
		Example:  generateExample("UY"),
	},
	{
		Iso2Code: "vi",
		Class:    "us-virgin-islands",
		Name:     "Us Virgin Islands",
		DialCode: "1",
		Example:  generateExample("VI"),
	},
	{
		Iso2Code: "uz",
		Class:    "uzbekistan",
		Name:     "Uzbekistan",
		DialCode: "998",
		Example:  generateExample("UZ"),
	},
	{
		Iso2Code: "vu",
		Class:    "vanuatu",
		Name:     "Vanuatu",
		DialCode: "678",
		Example:  generateExample("VU"),
	},
	{
		Iso2Code: "va",
		Class:    "vatican-city",
		Name:     "Vatican City",
		DialCode: "39",
		Example:  generateExample("VA"),
	},
	{
		Iso2Code: "ve",
		Class:    "venezuela",
		Name:     "Venezuela",
		DialCode: "58",
		Example:  generateExample("VE"),
	},
	{
		Iso2Code: "vn",
		Class:    "vietnam",
		Name:     "Vietnam",
		DialCode: "84",
		Example:  generateExample("VN"),
	},
	{
		Iso2Code: "wf",
		Class:    "wallis-and-futuna",
		Name:     "Wallis And Futuna",
		DialCode: "681",
		Example:  generateExample("WF"),
	},
	{
		Iso2Code: "eh",
		Class:    "western-sahara",
		Name:     "Western Sahara",
		DialCode: "212",
		Example:  generateExample("EH"),
	},
	{
		Iso2Code: "ye",
		Class:    "yemen",
		Name:     "Yemen",
		DialCode: "967",
		Example:  generateExample("YE"),
	},
	{
		Iso2Code: "zm",
		Class:    "zambia",
		Name:     "Zambia",
		DialCode: "260",
		Example:  generateExample("ZM"),
	},
	{
		Iso2Code: "zw",
		Class:    "zimbabwe",
		Name:     "Zimbabwe",
		DialCode: "263",
		Example:  generateExample("ZW"),
	},
	{
		Iso2Code: "ax",
		Class:    "aland-islands",
		Name:     "Aland Islands",
		DialCode: "358",
		Example:  generateExample("AX"),
	},
}
